### ISSUE TITLE
No node['sqitch']['engine']

### ISSUE THREAD

**Issue by josephholsten** [chef-cookbooks/sqitch#1]
causes an explosion at [resources/default.rb:26](https://github.com/opscode-cookbooks/sqitch/blob/master/resources/default.rb#L26), even if you pass a value to the resource.

simplest fix would be creating `attributes/default.rb` with the following:
```ruby
default['sqitch']['engine'] = 'pg'
```

**Comment by iennae** [comment]
Thanks! This has been resolved with PR #6. Thanks for your contribution to help this happen.
