### ISSUE TITLE
Resolve issues with install DBD::pg on Debian systems

### ISSUE THREAD

**Issue by iennae** [chef-cookbooks/sqitch#5]
### Cookbook version
0.5.0

### Platform Details
Debian (Centos has different issues)

### Scenario:
Converge the node successfully using default of postgresql as the engine.

### Steps to Reproduce:
kitchen converge default-debian-710

### Expected Result:
Successful converge on debian.

### Actual Result:
<details>

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[CPAN :install DBD::Pg] (/tmp/kitchen/cache/cookbooks/perl/libraries/provider_cpan_module.rb line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/local/bin/cpanm --quiet --notest DBD::Pg ----
           STDOUT:
           STDERR: ! Configure failed for DBD-Pg-3.5.3. See /root/.cpanm/work/1468459502.12894/build.log for details.
           ---- End output of /usr/local/bin/cpanm --quiet --notest DBD::Pg ----
           Ran /usr/local/bin/cpanm --quiet --notest DBD::Pg returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
</details>

Ubuntu similar but more information
<details>
           execute[CPAN :install DBD::Pg] (/tmp/kitchen/cache/cookbooks/perl/libraries/provider_cpan_module.rb line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/local/bin/cpanm --quiet --notest DBD::Pg ----
           STDOUT:
           STDERR: Constants from lexical variables potentially modified elsewhere are deprecated at /loader/0x14d69a8/aliased.pm line 1.
           ! Configure failed for DBD-Pg-3.5.3. See /root/.cpanm/work/1468459872.12495/build.log for details.
</details>
Wondering if pinning the version will help. This might actually be due to postgresql not being installed? Didn't dig too much into this error.

**Comment by tas50** [comment]
Fixed in master
